# Generated by Django 6.1.1 on 2026-09-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='Tumia tarehe ya kwanza ya mwezi, mfano 2026-09-01')),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=6)),
                ('amount_due', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='meters.meter')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer')], default='cash', max_length=15)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill')),
            ],
        ),
    ]
